default: &default
  adapter: postgresql
  encoding: unicode

development:
  <<: *default
  database: vile_weather_development

test:
  <<: *default
  database: vile_weather_test

production:
  <<: *default
  pool: 20
  database: vile_weather_production
  username: vile_weather
  password: <%= ENV['DATABASE_PASSWORD'] %>

staging:
  <<: *default
  database: vile_weather
  username: vile_weather